### PR TITLE
Update _helpers.tpl

### PR DESCRIPTION
**Pull request by cooling75**
For running on a K3s cluster on RPis I needed to add the initial delay for the health checks of the containers.

### CODE REVIEW

**Comment by smarthall** [comment]
Could you please bump the version, then run helm-docs and it should be good to merge :-)

**Comment by cooling75** [comment]
Thanks :) I wasn't aware of helm-docs until now.

**Comment by cooling75** [comment]
Hi, to be honest, I cannot see why it is not working?

**Comment by smarthall** [comment]
So the check that is failing is the check that ensures `helm-docs` has been run. This check is failing because your commit doesn't include the version information at the bottom of the file that `helm-docs` usually adds. I'm not sure why this is happening, but I've gone ahead and added it in order to get this working. :-)

**Comment by smarthall** [comment]
If you cherry-pick d949b90c15f3a69ed29079ff755cf835bcf2dc6f from my branch then you should be good to merge.

**Comment by cooling75** [comment]
Sorry, I am still a little confused, git is not my daily business.. ;)

**Comment by smarthall** [comment]
Closing this in favor of #22

**Pull request closed without merging**
